### ISSUE TITLE
Trying to filter on dt column while using alias for compare fields - Error 400 Unrecognized name: dt at [7:7]

### ISSUE THREAD

**Issue by emilycasebeer** [GoogleCloudPlatform/professional-services-data-validator#1008]
I am trying to compare two bigquery tables - TABLE1 with lowercase column names and a dt column, and then VIEW1 which is a view into TABLE1 with uppercase column names but contains no dt column. To get around the casing differences between TABLE1 and VIEW1 I am using field aliases for the comparison fields. 

I need to filter on dt for TABLE1, which is set up as my target table, but filter on nothing for VIEW1. See below for my yaml file for the compare - when I run this, I get an error: "AM-ERROR: Error 400 Unrecognized name: dt at [7:7]".  

Sometimes it seems like it is picking my target schema for my source table rather than the source schema. The schema names only differ by an "_r" and the table and view names are identical .

```
result_handler: {}
source: bigquery_conn
target: bigquery_conn
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: active
    source_column: ACTIVE
    target_column: active
  - cast: null
    field_alias: inactive
    source_column: INACTIVE
    target_column: inactive
  filter_status:
  - fail
  filters:
  - source: 1=1
    target: dt = DATE(2023,10,01)
    type: custom
  format: csv
  labels: []
  primary_keys:
  - cast: null
    field_alias: run_date
    source_column: RUN_DATE
    target_column: run_date
  - cast: null
    field_alias: id
    source_column: ID
    target_column: id
  random_row_batch_size: null
  schema_name: myproject.data
  table_name: MYVIEW
  target_schema_name: myproject.data_r
  target_table_name: MYTABLE
  threshold: 0.0
  type: Row
  use_random_rows: false
```

**Comment by helensilva14** [comment]
Hi @emilycasebeer! Could you please edit your `filters` block as below and check the results? If `null` causes an error, please try with `None` as well.

```
filters:
  - source: null
    target: dt = DATE(2023,10,01)
    type: custom
```

Also I would say for you to try to execute a validation from TABLE1 against TABLE1 itself with the filter to make sure it is being executed correctly. 

Let me know your progress afterwards!
