### ISSUE TITLE
Numeric overflow occurred during computation.

### ISSUE THREAD

**Issue by ShikharSundriyal** [GoogleCloudPlatform/professional-services-data-validator#1023]
When running a count comparison check between teradata and bigquery , its giving a Numeric overflow error.

Details :

Source -> Teradata
Target -> Bigquery 
Error message -> 
 [Teradata Database] [Error 2616] Numeric overflow occurred during computation.
Yaml File : 
```
result_handler: {}
source: td_conn
target: bq_conn
validations:
- aggregates:
  - field_alias: count__sale
    source_column: sale_bigint
    target_column: sale_bigint
    type: count
  - field_alias: sum__sale
    source_column: sale
    target_column: sale
    type: sum
  - field_alias: sum__cost
    source_column: cost
    target_column: cost
    type: sum
  calculated_fields:
  - depth: 0
    field_alias: sale_bigint
    source_calculated_columns:
    - sale
    target_calculated_columns:
    - sale
    type: cast
    default_cast: int64
  custom_query_type: column
  filter_status: null
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: null
  source_query: "select\n  cast(sale AS DECIMAL(18,2)) sale,\n  cast(cost\
    \ AS DECIMAL(18,2)) cost
   \ from db.sales\n\
    \  where date between '2023-01-01' and '2023-10-25'"
  table_name: null
  target_query: "select cast(sale as FLOAT64) sale , cast(cost\
    \ as FLOAT64) cost \
    \ from project.database.sales dtl\
    \ dtl\n  where dtl.date between DATE('2023-01-01') AND DATE('2023-10-25')"
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: false
```

Sql Generated using this Yaml : 
```sql
WITH t0 AS (
  SELECT t2."sale", t2."cost"
  FROM (
    select
      cast(sale AS DECIMAL(18,2)) sale,
      cast(cost AS DECIMAL(18,2)) cost
      from db.sales
      where CAL_DT between '2023-01-01' and '2023-10-25'
  ) t2
)
SELECT count(t1."sale_bigint") AS "count__sale",
       sum(t1."sale") AS "sum__sale",
       sum(t1."cost") AS "sum__cost"
FROM (
  SELECT t0.*, 
  CAST(t0."sale" AS BIGINT) AS "sale_bigint"
  FROM t0
) t1
```
The above sql is throwing a Numeric overflow exception. 
If we can have the cast at the outermost count the sql is working 

Expected SQL : 
```sql
WITH t0 AS (
  SELECT t2."sale", t2."cost"
  FROM (
    select
      cast(sale AS DECIMAL(18,2)) sale,
      cast(cost AS DECIMAL(18,2)) cost
      from db.sales
      where CAL_DT between '2023-01-01' and '2023-10-25'
  ) t2
)
SELECT CAST(count(t1."sale_bigint") AS BIGINT) AS "count__sale",
       sum(t1."sale") AS "sum__sale",
       sum(t1."cost") AS "sum__cost"
FROM (
  SELECT t0.*, 
  CAST(t0."sale" AS BIGINT) AS "sale_bigint"
  FROM t0
) t1
```

Is there a way we can have the cast at the outermost select.

**Comment by nehanene15** [comment]
Could you try adding a cast to the aggregate field like so:
```
- aggregates:
  - field_alias: count__sale
    source_column: sale_bigint
    target_column: sale_bigint
    type: count
    cast: int64
```
