### ISSUE TITLE
Can I validate MSSQL(SC) to Postgres(TC) and is there a documentation for that?

### ISSUE THREAD

**Issue by anandsaini18** [GoogleCloudPlatform/professional-services-data-validator#1112]
I was able to add the connections but unable to make data-validation validate command for my tables, please help

**Comment by nehanene15** [comment]
Yes, you can. What error are you seeing? All of our [examples](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md) apply to any source and target connection.

Please post the command and full stack trace.

**Comment by anandsaini18** [comment]
I was able to resolve that thank you for responding @nehanene15 
Although I was able to run data-validation validate row/column validations successfully on CLI but 
I am looking to automate that as I have more than 50 tables and I can't run every single command one by one.

For that I made yaml in this format
validations:
  - name: Validate User
    source_connection: my_mssql_conn
    target_connection: my_postgres_conn
    source_table: dbo.USER_DATA
    target_table: public.user_data
    hash_columns: "*"
    primary_keys:  CUST_ID
    use_random_row: true
    random_row_batch_size: 50
    
  running able yaml using this command :  data-validation configs run --config-file data-validation.yaml
  
  but getting this error and dont know how and why it is coming
  ERROR :
  File "/usr/local/lib/python3.8/dist-packages/data_validation/__main__.py", line 369, in config_runner
config_managers = build_config_managers_from_yaml(args, config_file_path)
File "/usr/local/lib/python3.8/dist-packages/data_validation/__main__.py", line 389, in build_config_managers_from_yaml
for config in yaml_configs[consts.YAML_VALIDATIONS]:
TypeError: 'NoneType' object is not iterable


@nehanene15 Would really appreciate if you can help me on this

**Comment by nehanene15** [comment]
@anandsaini18 Looks like there is an issue with your YAML config format. To create a YAML, use the `--config-file config.yaml` flag and then edit your fields as needed. See [this example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#store-validation-config-to-the-file) on how to generate a YAML config.

Typically, one YAML corresponds to one table validation, although you can have multiple validations that use the same source/target connection. Users typically write orchestration code to automate DVT validations per table (schema, table, row, etc) based on your validation requirements.

Example YAML running two separate row validations:
```yaml
result_handler: {}
source: teradata
target: bq
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: id
    source_column: ID
    target_column: ID
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: market
    source_column: market
    target_column: market
  random_row_batch_size: '10'
  schema_name: udf
  table_name: mascot
  target_schema_name: data_validator
  target_table_name: mascot
  threshold: 0.0
  type: Row
  use_random_rows: true
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: name
    source_column: name
    target_column: name
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: id
    source_column: ID
    target_column: ID
  random_row_batch_size: '20'
  schema_name: udf
  table_name: mascot
  target_schema_name: data_validator
  target_table_name: mascot
  threshold: 0.0
  type: Row
  use_random_rows: true
```
