### ISSUE TITLE
ForeignKeyConstraint with duplicate source column references are not supported error

### ISSUE THREAD

**Issue by bhga** [GoogleCloudPlatform/professional-services-data-validator#1278]
Hi Team,

We are using DVT for comparing DB2 (Linux Based) and BQ and while executing the DVT validations through cloud run job we are facing below error for tables with Foreign Key Constraint mentioned in DDLs.

**AM-ERROR: Error ForeignKeyConstraint with duplicate source column references are not supported.**

**Comment by helensilva14** [comment]
Hi @bhga! Please provide more information so we are able to help you.

- What type of validation are running: row, column, custom query? Please share the command or YAML used.
- Is BQ the source and DB2 the target or other way around?

**Comment by bhga** [comment]
Hi Helen,

For us the source is DB2 and target is BQ.
[table_count_validation.txt](https://github.com/user-attachments/files/17135322/table_count_validation.txt)

We are using schema ,column and row for running our validation. 
Please find attach YAML file for table_count validation (Type Column)

Thank You

**Comment by helensilva14** [comment]
Thanks for providing the YAML! I'm checking it and doing some tests. 

Meanwhile, is it possible for you to please test this same validation but changing to have BQ as source and DB2 as target?

**Comment by bhga** [comment]
Hi Helen,

Thanks for the response.
I tried re-validating with source this time as BQ and DB2 as target but still same error.
Please find attach YAML used for testing
[table_count_validation_bq_to_db2.txt](https://github.com/user-attachments/files/17144535/table_count_validation_bq_to_db2.txt)

Thanks!!

**Comment by helensilva14** [comment]
Hi @bhga! Still investigating this problem, but I found https://github.com/sqlalchemy/sqlalchemy/issues/5533 and https://github.com/ibmdb/python-ibmdbsa/issues/55 that are being helpful to gather some understanding.

Since changing source and target didn't change anything, can you please share what was the DVT command used to create this YAML config file? 

Example: 
```
data-validation validate column \
  -sc my_bq_conn \
  -tc my_bq_conn \
  -tbls bigquery-public-data.new_york_citibike.citibike_trips \
  -c citibike.yaml
```

**Comment by bhga** [comment]
Hi Helen,

We used the same command to generate yaml file as you mentioned in the above example.

Just that later we changed the details of source and target as per to our database,schema and table names

Thanks

**Comment by bhga** [comment]
Hi Helen,

Please let me know if you need more information on this.
Also it would be very helpful for us if you can provide any insight on the issue.

Thanks

**Comment by helensilva14** [comment]
> Please let me know if you need more information on this. Also it would be very helpful for us if you can provide any insight on the issue.

Hi @bhga! Sorry for my delayed response, it was a busy week. 

I realized we don't have a table on our DB2 test instance with FK constraints, so I'll create one today to hopefully be able to reproduce your issue and start checking how to fix it. 

> We used the same command to generate yaml file as you mentioned in the above example.
> Just that later we changed the details of source and target as per to our database,schema and table names

I see, thank you! Just wanted to check if you were generating your YAML files with other parameters.

**Comment by helensilva14** [comment]
@bhga could you please the DDL (CREATE TABLE statements) of the DB2 source and BQ target tables? Unfortunately I was not able to reproduce the error on my end.

If there's any sensitive info in the column names, you can send it by email: data-validator-eng@google.com

**Comment by bhga** [comment]
Hi Helen,

Thanks for checking on this!!, please find below sample Source DB2 and Target BQ table DDLs for your reference.

BigQuery Table DDL:

CREATE TABLE `dev.employee.employee_details`
(
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  EMP_ID INT64 NOT NULL,
  EMP_NAME STRING,
  EMP_PHONE_NUM STRING
);
 
DB2 Table DDL:

CREATE TABLE DB2.TY_EMPLOYEE_DETAILS (
	EMP_ID INTEGER NOT NULL,
	EMP_NAME CHAR(3),
	EMP_PHONE_NUM CHAR(8)
	CONSTRAINT TY_EMPLOYEE_DETAILS_PK PRIMARY KEY (EMP_ID),
	CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMP_ID) REFERENCES DB2.TY_EMPLOYEE(EMP_ID) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IYCC1 ON DB2.TY_EMPLOYEE_DETAILS (EMP_ID);

Please let me know if needed more details.

Thanks

**Comment by helensilva14** [comment]
Hello! Even using your sample DDLs and the exact YAML you shared initially I'm still not able to reproduce your error, please check it below 😕 This column validation executes with no errors with our DB2 instance, even having the Foreign Key constraint set.

Now I can only think about 2 other tests for you to perform:
1. Create a view on DB2 for the source table and try to use the view for column validation instead
2. Try a custom-query column validation similar to this: `data-validation validate custom-query column -sc mydb2 -tc bq -sq 'select count(*) AS total from db2inst1.ISSUE1278_EMPLOYEE_DETAILS_2' -tq 'select count(*) AS total from data_validator_issues.ISSUE1278_EMPLOYEE_DETAILS_2'` or using as a YAML config

```yaml
result_handler: {}
source: mydb2
target: bq
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  case_insensitive_match: false
  concat: null
  custom_query_type: column
  filter_status: null
  filters: []
  format: table
  hash: null
  labels: []
  random_row_batch_size: null
  schema_name: null
  source_query: select count(*) AS total from db2inst1.ISSUE1278_EMPLOYEE_DETAILS_2
  table_name: null
  target_query: select count(*) AS total from data_validator_issues.ISSUE1278_EMPLOYEE_DETAILS_2
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  trim_string_pks: false
  type: Custom-query
  use_random_rows: false
```

Executions screenshot:

![Image](https://github.com/user-attachments/assets/c756e75e-70a1-44c3-b175-8531450c588d)

```
db2 "CREATE TABLE ISSUE1278_EMPLOYEE_DETAILS_2 (
      CUST_ID INTEGER NOT NULL,
      EMP_NAME CHAR(3),
      EMP_PHONE_NUM CHAR(8),
      CONSTRAINT TY_EMPLOYEE_DETAILS_PK PRIMARY KEY(CUST_ID),
      CONSTRAINT FK_EMPLOYEE FOREIGN KEY(CUST_ID) REFERENCES ISSUE1278_CUSTOMER(CUST_ID) ON DELETE RESTRICT
);"
```

**Comment by bhga** [comment]
Hi Helen,

Thanks for the response!!!
Sure will check on your suggested options and will update you on same.

Meanwhile can you share the name of  DB2 instance used and yaml file used for testing db2 source table with FK constraints for column validation.

Thanks

**Comment by helensilva14** [comment]
Sure, here is the information I could get as I checked this documentation: https://www.ibm.com/docs/en/db2/11.5?topic=installing-verify-currently-installed-db2-version:

```
Database Connection Information

Database server        = DB2/LINUXX8664 11.5.8.0
SQL authorization ID   = DB2INST1
Local database alias   = TESTDB

[db2inst1@db2server ~]$ db2level
DB21085I  This instance or install (instance name, where applicable: 
"db2inst1") uses "64" bits and DB2 code release "SQL11058" with level 
identifier "0609010F".
Informational tokens are "DB2 v11.5.8.0", "s2209201700", "DYN2209201700AMD64", 
and Fix Pack "0".
Product is installed at "/opt/ibm/db2/V11.5".

[db2inst1@db2server ~]$ db2licm -l
Product name:                     "DB2 Community Edition"
License type:                     "Community"
Expiry date:                      "Permanent"
Product identifier:               "db2dec"
Version information:              "11.5"
Max amount of memory (GB):        "16"
Max number of cores:              "4"
Max amount of table space (GB):   "100"
Features:
IBM DB2 Performance Management Offering:              "Not licensed"
```

Regarding my testing tables, here are the commands:
```
db2 "CREATE TABLE ISSUE1278_CUSTOMER (
  CUST_ID INT NOT NULL PRIMARY KEY,
  CUST_NAME VARCHAR(50) NOT NULL,
  CUST_EMAIL VARCHAR(100)
);" 

db2 "INSERT INTO ISSUE1278_CUSTOMER (CUST_ID, CUST_NAME, CUST_EMAIL) VALUES
    (1, 'John Doe', 'john.doe@example.com'),
    (2, 'Jane Smith', 'jane.smith@example.com'),
    (3, 'David Lee', 'david.lee@example.com');"

 db2 "CREATE TABLE ISSUE1278_EMPLOYEE_DETAILS (
      CUST_ID INTEGER NOT NULL,
      EMP_NAME CHAR(3),
      EMP_PHONE_NUM CHAR(8),
      CONSTRAINT TY_EMPLOYEE_DETAILS_PK PRIMARY KEY(CUST_ID),
      CONSTRAINT FK_EMPLOYEE FOREIGN KEY(CUST_ID) REFERENCES ISSUE1278_CUSTOMER(CUST_ID) ON DELETE RESTRICT
);"

db2 "INSERT INTO ISSUE1278_EMPLOYEE_DETAILS VALUES
    (1, 'Doe', '12345678');"
```

And I used this YAML:

```yaml
result_handler: {}
source: mydb2
target: bq
validations:
- aggregates:
  - field_alias: rat_fgr_table_count
    source_column: null
    target_column: null
    type: count
  filter_status: null
  filters: []
  format: table
  labels:
  - !!python/tuple
    - validation_type
    - table_count_validation
  - !!python/tuple
    - dag_name
    - dvt_47_tables
  - !!python/tuple
    - stm_file
    - stm_47_tables.json
  random_row_batch_size: null
  schema_name: db2inst1
  table_name: ISSUE1278_EMPLOYEE_DETAILS
  target_schema_name: <GCP_PROJECT_ID>.data_validator_issues
  target_table_name: ISSUE1278_EMPLOYEE_DETAILS
  threshold: 0.0
  trim_string_pks: false
  type: Column
  use_random_rows: false
```
