### ISSUE TITLE
Add timezone conversions as a calculated field

### ISSUE THREAD

**Issue by renzokuken** [GoogleCloudPlatform/professional-services-data-validator#278]

**Comment by renzokuken** [comment]
There are two ways to tackle this. One is to set a default session timezone in the client init - this is probably the fastest path forward but will require testing to see that it's consistent.

The alternative is to build out the conversion syntax in the ibis_addons and propogate their usage up through the query builder. 

I'm going to try the first approach to see if we can just default the timezone to UTC if a flag is provided.

**Comment by nehanene15** [comment]
A fix for this is casting to a timestamp with a specific timezone in the YAML like so:
```
validations:
- calculated_fields:
- depth: 0
    field_alias: cast__START_TS
    source_calculated_columns:
    - SOURCE_START_TS
    target_calculated_columns:
    - SOURCE_START_TS
    type: cast
    default_cast: timestamp('UTC')
```
