### ISSUE TITLE
Multiple errors while trying to validate Hive table

### ISSUE THREAD

**Issue by hdwarakanath** [GoogleCloudPlatform/professional-services-data-validator#388]
I faced multiple errors while trying to use use DVT for validating migration of a table from Hive to BigQuery.

My sample data was generated using the data generation scripts in [hive-bigquery migration tool](https://github.com/GoogleCloudPlatform/professional-services/tree/main/tools/hive-bigquery/tests)

I have two run configurations for validations. Here is the first one

```
result_handler:
  project_id: *<PROJECT_ID>
  table_id: pso_data_validator.results
  type: BigQuery
  google_service_account_key_path: <PATH_TO_FILE>.json
source: hive_conn
target: bq_conn
validations:
- aggregates:
  - field_alias: count
    source_column: int_column
    target_column: int_column
    type: count
  - field_alias: sum
    source_column: int_column
    target_column: int_column
    type: sum
    cast: float64
  filters:
  - source: string_categorical_column="autumn"
    target: string_categorical_column="autumn"
    type: custom
  labels:
  - !!python/tuple
    - description
    - test
  schema_name: default
  table_name: parquet_partitioned
  target_schema_name: <PROJECT_ID>.dataset2
  target_table_name: test_partitioned_load
  threshold: 0.0
  type: Column
```

I had to get past 4 errors to get this running as described below:

- **Error 1:**
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: No module named 'hdfs'
    * **Resolved by:** `pip install hdfs`

- **Error 2:**
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: No module named 'thrift_sasl'
    * **Resolved by:** `pip install thrift_sasl`

- **Error 3:**
File "~/professional-services-data-validator/venv/lib/python3.7/site-packages/third_party/ibis/ibis_impala/api.py", line 61, in parse_type
    raise Exception(t)
Exception: date

    * **Resolved by:** Changing line 61 in api.py to
        `if "varchar" in t or "char" in t or "date" in t:`

- **Error 4:**
File "~/professional-services-data-validator/venv/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 1044, in <listcomp>
    ibis_types = [udf.parse_type(type.lower()) for type in types]
AttributeError: 'NoneType' object has no attribute 'lower'

    * **Resolved by:** Changing get_schema function in client.py to
```
def get_schema(self, table_name, database=None):
    """
    Return a Schema object for the indicated table and database

    Parameters
    ----------
    table_name : string
      May be fully qualified
    database : string, default None

    Returns
    -------
    schema : ibis Schema
    """
    qualified_name = self._fully_qualified_name(table_name, database)
    query = 'DESCRIBE {}'.format(qualified_name)

    # only pull out the first two columns which are names and types
    pairs = [row[:2] for row in self.con.fetchall(query)]

    names, types = zip(*pairs)
    ibis_types = []
    ibis_names = []
    for idx, name  in enumerate(names):
    	# All values before blank line in schema were valid so break on finding an empty string
        if not name:
            break
        ibis_names.append(name.lower())
        ibis_types.append(udf.parse_type(types[idx].lower()))

    return sch.Schema(ibis_names, ibis_types)
```

At this point, I could run the validation using the previous configuration. I then added grouped columns as part of the configuration as follows
```
  grouped_columns:
  - cast: null
    field_alias: date_column_group
    source_column: date_column
    target_column: date_column
```
This resulted in the below error

- **Error 5:**
impala.error.HiveServer2Error: Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 1:7 Expression not in GROUP BY key 'date_column'

I do see a [workaround](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/319#issuecomment-1044602665) for this. The first option "Pass this property as part of cluster creation" is not clear to me since changing the property after cluster creation  within Hive didn't help resolve the error, so I would like to know if there is something different to be done while starting the cluster. The second option "Run this command when you create hive connection in the source code." didn't work for me. It would be helpful to know where the change should be made in DVT to fix this error.

**Comment by nehanene15** [comment]
Thanks. For #1 and #2, I will be adding this to the documentation as installation reqs. 
For #3, I can push the fix for this change. 
For #4, I did override the `get_schema()` function [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_impala/api.py#L66) which fixed the 'NoneType' error. Did this fix not work for your use case?

@mnaveenkumar13 Any insight on the error #5 with the fix you found for group_by keys in Hive?

**Comment by nehanene15** [comment]
One path forward is setting the options in the Impala connection [here](https://github.com/ibis-project/ibis/blob/1.4.0/ibis/backends/impala/__init__.py#L121). You could do something like so after the ImpalaConnection is instantiated:
```
con = ImpalaConnection(pool_size=pool_size, **params)
options = dict(hive.groupby.orderby.position.alias='true')
con.set_options(options)
```
The [set_options() method](https://github.com/ibis-project/ibis/blob/1.4.0/ibis/backends/impala/client.py#L89) will allow you to add this property in Hive.

**Comment by ghost** [comment]
For error 1 and error 2- we need to install this package - pip3 install 'ibis-framework[impala]' - this installs all the dependency packages at one shot. Else, we might get different error for different operation. 

for Error 5 - while creating Dataproc cluster, go to "customize cluster" option and select "Cluster properties" and add Property. Or after cluster creation, you need to add this property in hive-site.xml and restart the hive service. I would prefer former, i.e add property while cluster creation. 

Property:  hive.groupby.orderby.position.alias=true

**Comment by hdwarakanath** [comment]
Thanks @nehanene15 and @mnaveenkumar13. Here are my updates:

Error 4 was resolved after I used the new version of `get_schema()`. Previously I was installing DVT by doing `pip install google-pso-data-validator` and it looks like the package still has the older version of code. When I used `pip install .` from the repo's directory this error was resolved.

For error 5, I couldn't fix it by making the changes in `ImpalaConnection` code, but the option of adding `hive.groupby.orderby.position.alias=true` as a property during cluster creation worked for me when I tried group by on a String column. However, there is still a problem when I try grouping on a date column as shown in the YAML config above. I get the below error

File "~/professional-services-data-validator/venv/lib/python3.7/site-packages/ibis/backends/impala/client.py", line 321, in _chunks_to_pandas_array
    numpy_type = _HS2_TTypeId_to_dtype[type_]
KeyError: 'DATE'

Not sure if this is happening because I cast the Date column to String while fixing Error 3. I see that there is a limitation in [Impala](https://stackoverflow.com/questions/48265651/can-hive-tables-that-contain-date-type-columns-be-queried-using-impala) for handling dates. Is there a workaround being built to handle date type?

**Comment by nehanene15** [comment]
It is likely this is happening when you cast the Date column to String in the `parse_type()` function. You could try removing that fix and instead casting to string within the validation config YAML itself like so:
```yaml
grouped_columns:
  - cast: string
    field_alias: date_column
    source_column: date_column
    target_column: date_column
```
