### ISSUE TITLE
Could someone send me a yaml with a DTM and STRING validation?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#468]
After reading the documentation I can't find any examples.  If there is documentation that I missed I would appreciate knowing about it.  Thank you!

**Comment by bnb012008** [comment]
Please?

**Comment by bnb012008** [comment]
To compare a string, I used the wis command line option to build a yaml and then modified the yaml so aggregate functions would be applied using the string length.  Is there any other way to compare two strings besides just using the length?

**Comment by nehanene15** [comment]
Here is an example YAML file with comparing the string column 'str' based on the sum of the length of the string column:
```yaml
result_handler:
  project_id: pso-kokoro-resources
  table_id: pso_data_validator.results
  type: BigQuery
source: my_bq_conn
target: my_bq_conn
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: sum__length__str
    source_column: length__str
    target_column: length__str
    type: sum
  calculated_fields:
  - depth: 0
    field_alias: length__str
    source_calculated_columns:
    - str
    target_calculated_columns:
    - str
    type: length
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: pso-kokoro-resources.hivetest
  table_name: tar
  target_schema_name: pso-kokoro-resources.hivetest
  target_table_name: tar
  threshold: 0.0
  type: Column
  use_random_rows: false
```

You can also do the following via CLI like so: `data-validation -v validate column -sc my_bq_conn -tc my_bq_conn -tbls pso-kokoro-resources.hivetest.tar -sum 'str' -bqrh pso-kokoro-resources.pso_data_validator.results`

And if you want to include string columns in wildcard aggregations ([documentation link](https://github.com/GoogleCloudPlatform/professional-services-data-validator#column-validations)):
`data-validation -v validate column -sc my_bq_conn -tc my_bq_conn -tbls pso-kokoro-resources.hivetest.tar -sum '*' -bqrh pso-kokoro-resources.pso_data_validator.results --wildcard-include-string-len`
