### ISSUE TITLE
Support casting primary keys 

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#494]
There should be support to cast a primary key block in the YAML like so:
```yaml
primary_keys:
  - cast: date
    field_alias: start_time
    source_column: start_time
    target_column: start_time
```

This issue is particularly focusing on a Teradata to BQ validaton
