### ISSUE TITLE
Failure to join source/target rows when source is Teradata and primary key contains a timestamp

### ISSUE THREAD

**Issue by rilkeanheart** [GoogleCloudPlatform/professional-services-data-validator#550]
This is closely related to a [previous issue](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/494).

We are using the format to request the casting of a field originating in Teradata as a timestamp. The resulting queries look as expected: 

CAST("SOURCE_START_TS" AS VARCHAR(255)) AS "cast__SOURCE_START_TS" now reads as...
CAST("SOURCE_START_TS" AS TIMESTAMP) AS "cast__SOURCE_START_TS"

However, the validation results still do not properly match source and target rows (each containing matching column values). Looking closely at the query results using the respective consoles, it looks as though the string version of each SOURCE_START_TS look slightly different. The BQ version contains the "UTC" while the Teradata does not. It's difficult to tell if this is an artifact of the console or the underlying representation.

Request: To help resolve, it would be great if the primary key column values used to join are included in the output table. This will make it easier to be certain they do match.

**Comment by nehanene15** [comment]
You can comment out line [142 in consts.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/consts.py#L142) in order to print the PK values out when using the text result handler. The column filter list removes the columns specified in the summarized text output, but you can include columns (such as PK) for debugging purposes.

**Comment by nehanene15** [comment]
There is a way to check the source vs target values being joined using comparison fields. You can replace 'calendar_date' in this example below with 'SOURCE_START_TS". The source and target agg values in the result of this validation will show the column value after a cast to timestamp for 5 random rows.

```yaml
result_handler: {}
source: td
target: td
validations:
- calculated_fields: []
  comparison_fields:
  - cast: timestamp
    field_alias: calendar_date
    source_column: calendar_date
    target_column: calendar_date
  dependent_aliases:
  - calendar_date
  - calendar_date_pk
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: timestamp
    field_alias: calendar_date_pk
    source_column: calendar_date
    target_column: calendar_date
  random_row_batch_size: '5'
  schema_name: Sys_Calendar
  table_name: CALENDAR
  target_schema_name: Sys_Calendar
  target_table_name: CALENDAR
  threshold: 0.0
  type: Row
  use_random_rows: true
```
