### ISSUE TITLE
String-type column names automatically converted to lower-case in generated config

### ISSUE THREAD

**Issue by aParthemer** [GoogleCloudPlatform/professional-services-data-validator#621]
I am trying to compare counts of specific columns between source table in Teradata and target table in BigQuery using the following command (table/schema names removed):

```
data-validation validate column \
    -sc TD \
    -tc BQ \
    -tbls ... \
    --count=COMP_ID,COMP_DESC \
    -c config.yaml
```

Note that in both source and targe tables, the column names are all upper case.

Here is the relevant part of the resulting config file:
```
result_handler: {}
source: TD
target: BQ
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  calculated_fields: []
  filter_status: null
  filters: []
  format: table
  labels: []
```

Notice how it does not pick up the specified columns `COMP_ID` and `COMP_DESC`.

Now, if I pass those column names as lower-case, the config generation successfully picks up the columns, but then generates them in lower case.  That is, when I run this command:

```
data-validation validate column \
    -sc TD \
    -tc BQ \
    -tbls ... \
    --count=comp_id,comp_desc \
    -c config.yaml
```

I get the following config:

```
result_handler: {}
source: TD
target: BQ
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: count__length__comp_id
    source_column: length__comp_id
    target_column: length__comp_id
    type: count
  - field_alias: count__length__comp_desc
    source_column: length__comp_desc
    target_column: length__comp_desc
    type: count
  calculated_fields:
  - depth: 0
    field_alias: length__comp_id
    source_calculated_columns:
    - comp_id
    target_calculated_columns:
    - comp_id
    type: length
  - depth: 0
    field_alias: length__comp_desc
    source_calculated_columns:
    - comp_desc
    target_calculated_columns:
    - comp_desc
    type: length
...etc
```

So, it's picking up the column names now, but since they are lower-case in the config the test cannot be executed.

ie. When I run `data-validation run-config -c config.yaml` on the above config, I get the following error:
```
ibis.common.exceptions.IbisTypeError: 'comp_id' is not a field in ['COMP_ID', 'COMP_DESC', 'COMP_TYPE', ...etc]
```

Finally, if I modify the generated config such that the desired fields are uppercase, then it's able to execute fine. Since config generation is a crucial part of our automation process, it won't work to manually change the column names for each validation config, hence this issue!

Any thoughts or recommended workarounds?

**UPDATE**

As a follow-up to this. It appears this *sort of* works when passing numeric columns rather than string columns. 

That is, using numeric column `COMP_LEVEL` I can get the desired result by running:
```
data-validation validate column \
    -sc TD \
    -tc BQ \
    -tbls ... \
    --count=comp_level \
    -c config.yaml
```

Note that I still have to pass the column as lower-case in order for it to work. If I pass `COMP_LEVEL` as uppercase, it simply defaults to null as shown in the first example. 

The above command produce this result:
```
result_handler: {}
source: TD
target: BQ
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: count__comp_level
    source_column: COMP_LEVEL
    target_column: COMP_LEVEL
    type: count
  calculated_fields: []
etc...
```

But again, this only seems to work when:
1. It is a numeric column
2. I pass the column name as lower-case (which is not how it is in the source system) to the data-validation command.
