### ISSUE TITLE
validate row: Oracle DATE format doesn't match PostgreSQL TIMESTAMP format

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#680]
The example that triggered this issue is an Oracle to PostgreSQL validation.
DVT casts date based columns to string without a format, formatting is left to the underlying engine. The Oracle default is often out of our control. Even if we can control it, Oracle DATE is to second precision where most other engines have DATE with day precision or a TIMESTAMP with fractional second precision. Again we are at the mercy of the underlying engines as to how they format the output of the CAST().

A suggested workaround for this specific Oracle to PostgreSQL project is to edit the config YAML file and for each Oracle DATE or TIMESTAMP column:

- Change type `cast` to `to_char`
- Add `default_to_char_fmt` of `"YYYY-MM-DD HH24:MI:SS"`

The project is to migrate 1000s of database therefore a manual process is not viable. Also the workaround only works for this specific project because Oracle and PostgreSQL share date formatting masks. An Oracle to BigQuery project would still be a problem.

I think a better solution is to redirect `cast` to `strftime` for any date based columns.

Approximate tasks would be:

- Support a type of `strftime` in YAML config file and support a format token too (either re-use `default_to_char_fmt` or add a new one specific to `strftime`)
- Change `config_manager.build_config_calculated_fields` to support a format parameter
- Add code to generate a suitable `strftime` format based on the column type. For example:
```
    def _strftime_format(self, column_type: Union[Date, Timestamp]) -> str:
        if isinstance(column_type, Timestamp):
            return "%Y-%m-%d %H:%M:%S"
        if isinstance(self.source_client, OracleClient):
            # Oracle DATE is a DateTime
            return "%Y-%m-%d %H:%M:%S"
        return "%Y-%m-%d"
```
- Use the above code on each source and target date-based column and pick the shortest mask for the config file. For example, if Oracle DATE is migrated to PostgreSQL date then we validate with the shorter `"%Y-%m-%d"` mask.
- Change `data_validation/config_manager.py build_config_calculated_fields()` to allow `cast` to be overridden when appropriate

I've mocked this up and it works for combinations of Oracle DATE/TIMESTAMP to PostgreSQL DATE/TIMESTAMP.

One vulnerability is that `strftime` does not currently cater for fractional seconds. Therefore the above validations are all at second precision. If we complete this issue then a follow on issue to support fractional seconds may be required.

**Comment by nehanene15** [comment]
We do support strftime with [custom calculated fields ](https://github.com/GoogleCloudPlatform/professional-services-data-validator#custom-calculated-fields) since it's supported in the[ Ibis API reference](https://ibis-project.org/docs/3.2.0/api/expressions/timestamps/#ibis.expr.types.temporal.TemporalValue.strftime).

It would look something like this in the YAML config:
```yaml
- calculated_fields:
  - depth: 0
    field_alias: replace_name
    source_calculated_columns:
    - date_column
    target_calculated_columns:
    - date_column
    type: custom
    ibis_expr: ibis.expr.api.TemporalValue.strftime
    params:
    - format_str: '%Y-%m-%d'
```

**Comment by nj1973** [comment]
I'd mocked it up like this but good if you have a better technique:
```
  - default_to_char_fmt: '%Y-%m-%d %H:%M:%S'
    depth: 0
    field_alias: cast__col_dt
    source_calculated_columns:
    - col_dt
    target_calculated_columns:
    - col_dt
    type: strftime
```
