### ISSUE TITLE
Data Validator - Column Validation - Default count aggregation 

### ISSUE THREAD

**Issue by Murli16** [GoogleCloudPlatform/professional-services-data-validator#693]
The data validator - column validation currently generates a default aggregated results as below screenshot indicated.

Is there any way to disable the default count result ?

Sample Command

```
data-validation validate column \
-sc bigquery_conn \
-tc bigquery_conn \
-tbls gcp-sandbox-1-359004.dvt_source_dataset.source_table=gcp-sandbox-1-359004.dvt_target_dataset.target_table \
-bqrh gcp-sandbox-1-359004.dvt_dataset.data_validation_results \
-c bq_count_validation.yaml \
-count station_id
```

This is expected to generate only **count_station_id**. However the below generated YAML generates an additional **count** row

```
result_handler:
  project_id: gcp-sandbox-1-359004
  table_id: dvt_dataset.data_validation_results
  type: BigQuery
source: bigquery_conn
target: bigquery_conn
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: count__station_id
    source_column: station_id
    target_column: station_id
    type: count
  calculated_fields: []
  filter_status: null
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: gcp-sandbox-1-359004.dvt_source_dataset
  table_name: source_table
  target_schema_name: gcp-sandbox-1-359004.dvt_target_dataset
  target_table_name: target_table
  threshold: 0.0
  type: Column
  use_random_rows: false
```

Attached is the output screenshot.
