### ISSUE TITLE
Data Validator - Custom Query - Row Validation - Does not generate comp fields or does not support comp fields 

### ISSUE THREAD

**Issue by Murli16** [GoogleCloudPlatform/professional-services-data-validator#694]
The data validator - custom query - row validation does not generate the comparison fields in YAML for the columns, neither supports **-comp-fields** attribute to specify the comparison fields.

Sample Command
```
data-validation validate custom-query \
-cqt row \
-sc bigquery_conn \
-tc bigquery_conn \
-bqrh gcp-sandbox-1-359004.dvt_dataset.data_validation_results \
-c bq_row_custom_query_validation_3.yaml \
-sqf source.sql \
-tqf target.sql \
-pk station_id \
-filter "station_id in (2712, 1004):station_id in (2712, 1004)"
```

Running this command issues an error **TypeError: reduce() of empty sequence with no initial value**

This seems due to the fact comparison fields are not generated by default based on query or does not support explicit mentioning of comp-fields.

```
result_handler:
  project_id: gcp-sandbox-1-359004
  table_id: dvt_dataset.data_validation_results
  type: BigQuery
source: bigquery_conn
target: bigquery_conn
validations:
- calculated_fields: []
  custom_query_type: row
  filter_status: null
  filters:
  - source: station_id in (2712, 1004)
    target: station_id in (2712, 1004)
    type: custom
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: station_id
    source_column: station_id
    target_column: station_id
  random_row_batch_size: null
  schema_name: null
  source_query: select station_id, name, status from gcp-sandbox-1-359004.dvt_source_dataset.source_table
  table_name: null
  target_query: select station_id, name, status from gcp-sandbox-1-359004.dvt_target_dataset.target_table
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: false
```

Current workaround is to generate the YAML and add the comparison fields block manually to the YAML and execute.

The custom query for row validation support only exists for concat and hash.

This request is for supporting comp-fields as well for the custom query row validation
