### ISSUE TITLE
ValueError: Expected source and target to have same schema, got source: ['id', 'DataBaseName', 'TableName', 'TypeDesc', 'TableType'] target: ['id']

### ISSUE THREAD

**Issue by shivanshusoni185** [GoogleCloudPlatform/professional-services-data-validator#823]
I got this error when I tried to  perform row validation source(MSSQL) and target is(BQ)  In the source table column name is like  'DataBaseName', 'TableName', 'TypeDesc', 'TableType and in target table is like id , databasename , tablename , typedesc,tabletype  .

Is there any way to perfrom row level validation which ignore that kind  of scenario.

ValueError: Expected source and target to have same schema, got source: ['id', 'DataBaseName', 'TableName', 'TypeDesc', 'TableType'] target: ['id']

**Comment by nehanene15** [comment]
You can use the YAML config files to specify a different source/target column name like so:
```
result_handler: {}
source: my_bq_conn
target: my_bq_conn
validations:
  comparison_fields:
  - cast: null
    field_alias: replace_name
    source_column: TableName
    target_column: tablename
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: id
    source_column: id
    target_column: id
  random_row_batch_size: '5'
  schema_name: bigquery-public-data.new_york_citibike
  table_name: citibike_stations
  target_schema_name: bigquery-public-data.new_york_citibike
  target_table_name: citibike_stations
  threshold: 0.0
  type: Row
  use_random_rows: true
```
