### ISSUE TITLE
Count validation : Teradata to BQ

### ISSUE THREAD

**Issue by warunk9** [GoogleCloudPlatform/professional-services-data-validator#885]
Observation:
- while count validation , larger counts from teradata is failing as it needs casting for BIGINTEGER

**Comment by nehanene15** [comment]
Does the `--cast-to-bigint` flag help with this? What is the data type of the column that the sum is being run over?

**Comment by warunk9** [comment]
not actually, its not sum I am calculating , it is count validation which gives me this error.
<img width="621" alt="Screenshot 2023-06-15 at 7 48 06 AM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/123057617/db8cdae3-32df-4b30-af68-56d89b631c43">

**Comment by nehanene15** [comment]
In that case, you will need to cast the count to a BIGINT like so:
```yaml
result_handler: {}
source: my_bq_conn
target: my_bq_conn
validations:
- aggregates:
  - field_alias: count_cast__int
    source_column: cast__int
    target_column: cast__int
    type: count
  calculated_fields:
  - depth: 0
    field_alias: cast__int
    source_calculated_columns:
    - int
    target_calculated_columns:
    - int
    type: cast
    default_cast: int64
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: project.dataset
  table_name: my_table
  target_schema_name: project.dataset
  target_table_name: my_table
  threshold: 0.0
  type: Column
  use_random_rows: false
```
