### ISSUE TITLE
Schema validation: how to translate the "--exclusion-columns" command of the cli into json

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#901]
I need to implement a schema validation of 2 tables using a json file. How can I add the --exclusion-columns cli command into a json?

**Comment by helensilva14** [comment]
Hi @elena-gottardi-nttdata! We admit we don't have clear instructions right now about this and we will work on that, thanks for bringing this problem! 

For your case it will probably be something like the following:

```json5
BQ_CONN = {"source_type": "BigQuery", "project_id": project}

GROUPED_CONFIG_COUNT_VALID = {
    "source_conn": BQ_CONN,
    "target_conn": BQ_CONN,
    "type": "Schema",
    "table_name": "citibike_trips",
    "schema_name": "bigquery-public-data.new_york_citibike",
    "target_schema_name": "bigquery-public-data.new_york_citibike",
    "target_table_name": "citibike_trips",
    "labels": [],
    "threshold": 0.0,
    "format": "table",
    "result_handler": None,
    "filters": [],
    "use_random_rows": None,
    "random_row_batch_size": None,
    "filter_status": None,
    "exclusion_columns": [
        "gender",
        "customer_plan"
    ],
    "allow_list": ""
}
```

You can use this command `data-validation validate schema -sc bq -tc bq -tbls bigquery-public-data.new_york_citibike.citibike_trips -ec gender,customer_plan -c citibike.yaml` as reference to generate the YAML config file below, even though there are some differences between our YAML and JSON config structures [as mentioned here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow/README.md#limitations).

```yaml
result_handler: {}
source: bq
target: bq
validations:
- allow_list: ''
  exclusion_columns:
  - gender
  - customer_plan
  filter_status: null
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: bigquery-public-data.new_york_citibike
  table_name: citibike_trips
  target_schema_name: bigquery-public-data.new_york_citibike
  target_table_name: citibike_trips
  threshold: 0.0
  type: Schema
  use_random_rows: null

```
 
 Let me know if this helped you!
