### ISSUE TITLE
Teradata row validation: CHAR PK adds trailing whitespace

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#927]
When running a Teradata to BQ row validation with a PK of type CHAR, there is extra whitespace added in Teradata causing a data mismatch.

Command to reproduce:
`data-validation -v validate row -sc teradata -tc bq -tbls udf.dvt_core_types=pso_data_validator.dvt_core_types -pk col_char_2 -hash col_dec_38`

**Comment by nehanene15** [comment]
This seems to be an issue with teradatasql specifically for 'CHAR' columns: https://stackoverflow.com/questions/70753146/problem-with-spaces-added-while-running-queries-with-the-teradatasql-package

The solution here would be to manually add an 'rstrip' to the CHAR primary key column like so:
```yaml
result_handler: {}
source: teradata
target: bq
validations:
- calculated_fields:
  - depth: 0
    field_alias: rstrip_col_char_2
    source_calculated_columns:
    - col_char_2
    target_calculated_columns:
    - col_char_2
    type: rstrip
  - depth: 0
    field_alias: cast__col_dec_38
    source_calculated_columns:
    - col_dec_38
    target_calculated_columns:
    - col_dec_38
    type: cast
  - depth: 1
    field_alias: ifnull__cast__col_dec_38
    source_calculated_columns:
    - cast__col_dec_38
    target_calculated_columns:
    - cast__col_dec_38
    type: ifnull
  - depth: 2
    field_alias: rstrip__ifnull__cast__col_dec_38
    source_calculated_columns:
    - ifnull__cast__col_dec_38
    target_calculated_columns:
    - ifnull__cast__col_dec_38
    type: rstrip
  - depth: 3
    field_alias: upper__rstrip__ifnull__cast__col_dec_38
    source_calculated_columns:
    - rstrip__ifnull__cast__col_dec_38
    target_calculated_columns:
    - rstrip__ifnull__cast__col_dec_38
    type: upper
  - depth: 4
    field_alias: concat__all
    source_calculated_columns:
    - upper__rstrip__ifnull__cast__col_dec_38
    target_calculated_columns:
    - upper__rstrip__ifnull__cast__col_dec_38
    type: concat
  - depth: 5
    field_alias: hash__all
    source_calculated_columns:
    - concat__all
    target_calculated_columns:
    - concat__all
    type: hash
  comparison_fields:
  - cast: null
    field_alias: hash__all
    source_column: hash__all
    target_column: hash__all
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: rstrip_col_char_2
    source_column: rstrip_col_char_2
    target_column: rstrip_col_char_2
  random_row_batch_size: null
  schema_name: udf
  table_name: dvt_core_types
  target_schema_name: pso_data_validator
  target_table_name: dvt_core_types
  threshold: 0.0
  type: Row
  use_random_rows: false
```

Only caveat here is this won't work with random rows, only filters.
