### ISSUE TITLE
weird error message on wrong cast type (`datetime`) in config

### ISSUE THREAD

**Issue by florisvink** [GoogleCloudPlatform/professional-services-data-validator#948]
`datetime` is not a valid value for `cast:` in the YAML config. Normally you can a clear error like:

```
...
validations:
- calculated_fields: []
  comparison_fields:
  - cast: some_invalid_cast_type
    field_alias: dd
    source_column: dd
    target_column: dd
...
```
..results in the error: `PM-ERROR: Error expected one of '!', 'array', 'bigdecimal', 'bignumeric', 'binary', 'bool', 'boolean', 'bytes', 'char', 'date', 'decimal', 'double', 'float', 'float16', 'float32', 'float64', 'geography', 'geometry', 'halffloat', 'inet', 'int', 'int16', 'int32', 'int64', 'int8', 'interval', 'json', 'linestring', 'macaddr', 'map', 'multilinestring', 'multipoint', 'multipolygon', 'null', 'point', 'polygon', 'set', 'str', 'string', 'struct', 'time', 'timestamp', 'uint16', 'uint32', 'uint64', 'uint8', 'uuid', 'varchar'`

However if you accidentally put `datetime` in the cast you field like:
```
...
validations:
- calculated_fields: []
  comparison_fields:
  - cast: datetime
    field_alias: dd
    source_column: dd
    target_column: dd
...
```
you get the weird error: ` Error expected 'EOF'`.
