### ISSUE TITLE
Case sensitivity issue with Snowflake row validation

### ISSUE THREAD

**Issue by henrihem** [GoogleCloudPlatform/professional-services-data-validator#954]
Data validation for row fails with primary key. This happens with Snowflake as source and Bigquery as target.

Giving primary key as lowercase:
`data-validation validate row --use-random-row --random-row-batch-size 10 --hash "*" \
    -sc sf_conn \
    -tc bq_conn \
    -tbls <tables> \
    --primary-keys "dv_id"`

Will result in:
`ibis.common.exceptions.IbisTypeError: Column 'DV_ID' is not found in table. Existing columns: 'hash__all', 'dv_id'.`

Giving primary key as uppercase:
`data-validation validate row --use-random-row --random-row-batch-size 10 --hash "*" \
    -sc sf_conn \
    -tc bq_conn \
    -tbls <tables> \
    --primary-keys DV_ID`

Will result in:
`ibis.common.exceptions.IbisTypeError: Column 'dv_id' is not found in table. Existing columns: 'hash__all', 'DV_ID'.`

**Comment by nehanene15** [comment]
This is because the PKs are stored in different cases on Snowflake (uppercase) and BigQuery (lowercase).

You will need to use a YAML config to specify this difference. Generate the config like so: `data-validation validate row --use-random-row --random-row-batch-size 10 --hash "*" \ -sc sf_conn \ -tc bq_conn \ -tbls <tables> \ --primary-keys "dv_id" -c config.yaml`

And update the primary keys block like so:
```yaml
primary_keys:
  - cast: null
    field_alias: dv_id
    source_column: DV_ID
    target_column: dv_id
```

**Comment by henrihem** [comment]
Thank you for your help.
However, I'm still facing issues event with the example primary keys provided:
```
primary_keys:
  - cast: null
    field_alias: dv_id
    source_column: DV_ID
    target_column: dv_id
```

`08/28/2023 09:24:10 AM-ERROR: Error Column 'dv_id' is not found in table. Existing columns: 'DV_ID'. occurred while running config file example.yaml. Skipping it for now.`

Tested it with dry-run and the query itself looks to be fine.
